# $schema: https://json.schemastore.org/github-workflow.json

name: Run release-please

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  release-please:
    name: release-please
    uses: ./.github/workflows/release-please.yaml
    with:
      app-client-id: ${{ vars.RELEASE_APP_CLIENT_ID }}
    secrets:
      app-private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
